model = "gpt-5.2"
model_reasoning_effort = "xhigh"
# model_reasoning_summary = "concise"
model_verbosity = "low"
# Disable automatic compaction entirely
model_auto_compact_token_limit = 0

[notice]
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

# boolean only
[features]
rmcp_client = true
web_search_request = true
view_image_tool = true
ghost_commit = false
undo = false
unified_exec = true
parallel = true